FROM node:alpine AS build
WORKDIR /app
COPY ./ ./
RUN npm ci
RUN npm run build

FROM node:alpine AS run
WORKDIR ./app
COPY --from=build /app/package.json ./
COPY --from=build /app/package-lock.json ./
COPY --from=build /app/.next ./

RUN npm ci
ENTRYPOINT [ "npm", "run", "start" ] 
EXPOSE 80