version: '3.8'

services:
  ui:
    image: uidemo:latest
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '0.25'
          memory: 50M
        reservations:
          cpus: '0.1'
          memory: 20M
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3          
    ports: 
      - target: 443
        published: 4443
        protocol: tcp
      - target: 80
        published: 8080
        protocol: tcp

  api: